select 
AutoId,
replace(replace(replace([Content],char(10),' '),char(13),' '),char(9),' ') as [Content],
Accessory,
AttentionCount,
Book,
BrandCode,
CauseId,
Contact,
Question.CreateDate,
DealerCode,
DUserCode,
DutyGroupCode,
DutyNote,
Email,
HasDealerRead,
InReply,
InReplyState,
IsComplaint,
IsElite,
IsEncrypt,
LastReplyDate,
LockBy,
Question.Modifier,
Question.ModifyDate,
OrderCode,
PAC,
PartDescCN,
PartDescEN,
PartNumber,
ProductDate,
Province,
QuestionCode,
Question.QuestionState,
QuestionState.QuestionStateDescCN as QuestionStateName,
QuestionType,
QuestionType.NameCN as QuestionTypeName,
Reason,
ReplyCount,
ShipCode,
ShipWarehouse,
SPEOrSPECS,
Telphone,
Title,
VIN
from Question
left join QuestionType on Question.QuestionType=QuestionType.Code
left join QuestionState on Question.QuestionState=QuestionState.QuestionState
where Question.CreateDate between :begin and :end