select 
AutoId,
replace(replace(replace([Content],char(10),' '),char(13),' '),char(9),' ') as [Content],
Accessory,
AttentionCount,
Book,
BrandCode,
Contact,
Question.CreateDate,
DealerCode,
DUserCode,
DutyGroupCode,
DutyNote,
Email,
HasDealerRead,
InReply,
InReplyState,
IsComplaint,
IsElite,
IsEncrypt,
LastReplyDate,
LockBy,
Question.Modifier,
Question.ModifyDate,
OrderCode,
PAC as pac,
PartDescCN,
PartDescEN,
PartNumber,
ProductDate,
Province,
QuestionCode,
Question.QuestionState,
QuestionState.QuestionStateDescCN as QuestionStateName,
QuestionType,
Reason,
ReplyCount,
ShipCode,
ShipWarehouse,
SPEOrSPECS as speorspecs,
Telphone,
Title,
VIN as vin
from Question
left join QuestionType on Question.QuestionType=QuestionType.Code
left join QuestionState on Question.QuestionState=QuestionState.QuestionState
where Question.CreateDate between ? and ?